version: '3'

services:
  nginx:
    image: nginx
    depends_on:
    - jenkins
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    networks:
    - proxy
    links:
    - jenkins

  jenkins:
    image: radcom/jenkins:latest
    volumes:
    - jenkins_data:/var/jenkins_home
    - jenkins_downloads:/var/jenkins_home/downloads
    - jenkins_jobs:/var/jenkins_home/jobs
    ports:
    - "8080:8080"
    - "50000:50000"
    networks:
    - proxy

volumes:
  jenkins_data: {}
  jenkins_downloads: {}
  jenkins_jobs: {}

networks:
  proxy:
